org: mirandasalazar
service: api-album

provider:
  name: aws
  runtime: python3.12
  memorySize: 512
  timeout: 29
  iam:
    role: arn:aws:iam::060098569939:role/LabRole
  environment:
    TABLE_NAME: ${sls:stage}-t_album

functions:
  getAlbums:
    handler: albumQuery.lambda_handler
    events:
      - http:
          path: albums
          method: get
          responses:
            '200':
              description: Lista de álbumes recuperada con éxito
            '400':
              description: Parámetros inválidos proporcionados
            '404':
              description: No se encontraron álbumes
            '500':
              description: Error interno del servidor o error en la base de datos

  deleteAlbum:
    handler: deleteAlbum.lambda_handler
    events:
      - http:
          path: albums
          method: delete
          responses:
            '200':
              description: Ábum eliminado correctamente
            '400':
              description: Datos inválidos proporcionados
            '404':
              description: Álbum no encontrado
            '500':
              description: Error interno del servidor o error en la base de datos

  postAlbum:
    handler: postAlbum.lambda_handler
    events:
      - http:
          path: albums
          method: post
          responses:
            '201':
              description: Álbum creado exitosamente
            '400':
              description: Datos inválidos proporcionados
            '404':
              description: Álbum no encontrado
            '500':
              description: Error interno del servidor o error en la base de datos

resources:
  Resources:
    AlbumTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: artist_id
            AttributeType: S
          - AttributeName: date#genre
            AttributeType: S
          - AttributeName: album_uuid
            AttributeType: S
        KeySchema:
          - AttributeName: artist_id
            KeyType: HASH
          - AttributeName: date#genre
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: UUIDIndex
            KeySchema:
              - AttributeName: album_uuid
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        LocalSecondaryIndexes:
          - IndexName: Artist_DateIndex
            KeySchema:
              - AttributeName: artist_id
                KeyType: HASH
              - AttributeName: date#genre
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        BillingMode: PAY_PER_REQUEST
